spring:
  application:
    name: token-order
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ZellleTransactionOrder
logging:
  level:
    root: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 9095
